#
# Cleans up a GitHub PR
#
name: Delete Environment (default settings)

on:
  delete:
    branches-ignore:
      - main
      - dev

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: renbrent/weather-app@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.DELETE_ENV }}
          environment: github-pages
